import dotenv from 'dotenv';

dotenv.config();

interface ENV extends NodeJS.ProcessEnv {
  PORT: string
  MONGO_URL: string
  FRONTEND_URL: string
  MONGO_TEST_URL: string
  PASSWORD_TOKEN_SECRET: string
  TRANSPORTER_HOST: string
  TRANSPORTER_PORT: string
  TRANPORTER_USER: string
  TRANSPORTER_PASS: string
}
const {
  PORT, MONGO_URL, FRONTEND_URL, MONGO_TEST_URL, PASSWORD_TOKEN_SECRET, TRANSPORTER_HOST, TRANSPORTER_PORT, TRANPORTER_USER, TRANSPORTER_PASS,
} = process.env as ENV;

export {
  MONGO_URL, FRONTEND_URL, PORT, MONGO_TEST_URL, PASSWORD_TOKEN_SECRET, TRANSPORTER_HOST, TRANSPORTER_PORT, TRANPORTER_USER, TRANSPORTER_PASS,
};
